const s={questions:[],current:null,category:null,seen:new Set()};
const v={loading:document.querySelector('#loading'),error:document.querySelector('#error'),home:document.querySelector('#home'),question:document.querySelector('#question'),answer:document.querySelector('#answer')};
const show=n=>{Object.values(v).forEach(x=>x.classList.add('hidden'));v[n].classList.remove('hidden');scrollTo(0,0)};
async function load(){try{const r=await fetch('data/questions.json',{cache:'no-store'});if(!r.ok)throw Error(r.status);const d=await r.json();s.questions=Array.isArray(d)?d:[d];if(!s.questions.length)throw Error('No published questions found');renderCategories();show('home')}catch(e){document.querySelector('#errorText').textContent='The question file could not be loaded.';show('error')}}
function renderCategories(){const c={};s.questions.forEach(q=>{const k=(q.category||'Uncategorized').trim();c[k]=(c[k]||0)+1});const box=document.querySelector('#categories');box.innerHTML='';Object.entries(c).sort().forEach(([k,n])=>{const b=document.createElement('button');b.className='category';b.innerHTML=`${k}<span class="count">${n} ${n===1?'question':'questions'}</span>`;b.onclick=()=>{s.category=k;s.seen.clear();nextQuestion()};box.appendChild(b)})}
function nextQuestion(){const pool=s.questions.filter(q=>(q.category||'').trim()===s.category);let cand=pool.filter(q=>!s.seen.has(q.id));if(!cand.length){s.seen.clear();cand=pool}const q=cand[Math.floor(Math.random()*cand.length)];s.current=q;s.seen.add(q.id);qCat.textContent=q.category||'';qDiff.textContent=q.difficulty||'';qId.textContent=q.id?`Question ID: ${q.id}`:'';qText.textContent=q.question||'';show('question')}
answerBtn.onclick=()=>{const q=s.current;if(!q)return;aCat.textContent=q.category||'';aDiff.textContent=q.difficulty||'';aId.textContent=q.id?`Question ID: ${q.id}`:'';aQuestion.textContent=q.question||'';aText.textContent=q.answer||'';aRef.textContent=q.reference||'No reference provided';show('answer')};
backBtn.onclick=()=>{s.current=null;s.category=null;s.seen.clear();show('home')};
nextBtn.onclick=()=>{s.current=null;s.category=null;s.seen.clear();show('home')};
feedbackBtn.onclick=()=>{const q=s.current;if(!q)return;const subject=`Bible Trivia Beta Feedback — ${q.id||'Question'}`;const body=[`Question ID: ${q.id||''}`,`Category: ${q.category||''}`,`Difficulty: ${q.difficulty||''}`,`Question: ${q.question||''}`,`Answer: ${q.answer||''}`,`Reference: ${q.reference||''}`,'','FEEDBACK','What issue did you notice?'].join('\n');location.href=`mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`};
load();